### ISSUE TITLE
Wrong continent name for some POR entries

### ISSUE THREAD

**Issue by da115115** [opentraveldata/optd#11]
The [ori_por_public.csv file](https://github.com/opentraveldata/optd/blob/trunk/refdata/ORI/ori_por_public.csv?raw=true) contains POR (point of reference) entries containing non standard continent names (e.g., America, Atlantic)

``` shell
$ cut -d'^' -f20 ./ori_por_public.csv | sort -u
Africa * 
America 
Antarctica * 
Asia * 
Atlantic 
Australia 
continent_name 
Europe * 
Indian 
North America * 
Oceania * 
Pacific 
South America * 
```

**Comment by da115115** [comment]
The mapping between countries and their related continents must be extracted from Geonames and made available when generating the ORI-maintained file of POR. A new AWK script may be necessary.

**Comment by alexprengere** [comment]
You can map the `country_code` to the `continent` using GeoBase:

``` shell
$  GeoBase -b countries -s code continent -q 
#code^continent
BD^AS
BE^EU
BF^AF
BG^EU
BA^EU
...
```

Then you can finish replacing the continent codes by their names (you can also get this mapping by `GeoBase`).
