### ISSUE TITLE
Fix the coordinates of the KUS POR

### ISSUE THREAD

**Issue by dchoe** [opentraveldata/optd#19]
The [Kulusuk Airport](http://www.search-airports.com/search/?q=kus&z=14) needs some care:
- The name should be translated into English
- The coordinates should be fixed

**Comment by da115115** [comment]
Fixed by b3aa168cccc9f00a848cdf55db298a6ab7b1e529 ([b3aa168 -- LL6902-6903](http://github.com/opentraveldata/optd/commit/b3aa168cccc9f00a848cdf55db298a6ab7b1e529#diff-56f5b1ee42ceaa14e4101670cf175adbL6902))
