### ISSUE TITLE
[ori_por_public] Building the mapping city_code to POR directly in the file

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/optd#2]
In the ori_por file, there is the mapping POR to city_code, like:
ORY^Orly^PAR

The reverse mapping may also be interesting to avoid looping through the whole file each time we want to know which POR are in the city, for example something like:
PAR^paris^PAR^ORY,CDG

Where the new field ORY,CDG gives the list of POR associated to the city PAR.

**Comment by da115115** [comment]
Done: 25c160c5eecb313066263c537a57e4a62b2e2de4
Typically, Paris gives:

``` text
PAR^[...]^Paris^[...]^PAR^Paris^Paris^BVA,CDG,JDP,JPU,LBG,ORY,POX,TNF,VIY,XCR,XEX,XGB,XHP,XJY,XPG,XTT^^C^http://en.wikipedia.org/wiki/Paris
```

**Comment by alexprengere** [comment]
Great work!
I just integrated this new data in [GeoBases](https://github.com/opentraveldata/geobases).
You may update GeoBase by just installing it again: `git pull` and `python setup.py install --user`.
To remove old versions, you can use `pip`: `pip uninstall GeoBases` (possibly several times).

A bit of visualization to check the data.

```
$ GeoBase -E tvl_por_list@raw -e "" -r  -i _ _ tvl_por_list -m -M _ __none__ _ __none__
```

This command will draw:
1. tvl_por_list not empty (`-r` for _not_ on the `-e`)
2. we index using the tvl_por_list (meaning keys are generated using this field, details with `--warnings`)
3. we draw the results on a map, with no markers and no circles

The map is empty, but click on the _duplicates_ button, you will see lines drawn between points which have the same tvl_por_list, since we re-indexed using this field (2.). All lines are pretty small, meaning entries with the same tvl_por_list are very close (except one or two things), it seems to be working :)

If we wanted to draw lines between elements of all travel por lists, we could use directly the Python API (I would say twenty lines of codes :)). Or, assuming all elements of a travel por list have the same `city_code` field (I am not sure it is the case), we could just index using the `city_code`. Here we draw lines between same city_codes:

```
$ GeoBase -E tvl_por_list@raw -e "" -r  -i _ _ city_code -m -M _ __none__ _ __none__
```

**Comment by da115115** [comment]
Cool, many thanks for those commands!
Note that when I issue the second form of the command, i.e.:

```
$ GeoBase -E tvl_por_list@raw -e "" -r  -i _ _ city_code -m -M _ __none__ _ __none__
```

There are some "false" duplicates, such as for instance FMO on the 
![following screen capture](https://f.cloud.github.com/assets/148716/100880/45f423ce-6882-11e2-8255-f7109c1be9db.png).
It seems an issue related to the tvl_por_list data source only, as the classical:

```
$ GeoBase FMO
```

does not mention any duplicate.

**Comment by alexprengere** [comment]
`FMO` does seem to have a duplicate when you do

``` shell
$ GeoBase FMO
```

You have to look at the field `__dup__`, it has a duplicate named `FMO@1`.
When performing commands like this, you are browsing the `ori_por` source which only relies on the iata_code for indexation. For indexation based on iata_code _and_ location_type, you may either use `ori_por_multi` and perform a search on the field iata_code like this:

``` shell
$ GeoBase -b ori_por_multi -E iata_code -e FMO 
```

Or change indexation on the fly for ori_por, and do the same search, like this:

``` shell
$ GeoBase -i _ _ iata_code/location_type _ -E iata_code -e FMO 
```

**Comment by da115115** [comment]
Sure, but unless I am mistaken, even:

``` shell
$ GeoBase -b ori_por_multi -E iata_code -e FMO 
```

gives two POR (an airport and the corresponding city) having exactly the same geographical coordinates. So, I do not understand why one of them seems to be located in France (see the above screen capture)...

**Comment by alexprengere** [comment]
This is because the screenshot shows lines between POR sharing the same _city_code_.
Indeed the two POR sharing the same _iata_code_ have the same coordinates. 

But there is a third POR having FMO as city_code, this is ZPE:

``` shell
$ GeoBase -E city_code -e FMO --map
```
