### ISSUE TITLE
Panevezys (PNV): wrong latitude & longitude

### ISSUE THREAD

**Issue by lnarboni** [opentraveldata/optd#21]
As of January 2014, [Panevezys (PNV) is located by Search for Travel](http://search-travel.org/search/?q=pnv&z=12) in the Atlantic Ocean.

Indeed, [PNV is referenced in RefData/ORI](http://github.com/opentraveldata/optd/blob/trunk/refdata/ORI/ori_por_best_known_so_far.csv) as located at [(46.07,-11.13)](http://maps.google.com/maps?q=46.07+-11.13&hl=en&ll=46.07,-11.13&spn=101.998878,259.628906&sll=55.73001,24.46003&sspn=0.042241,0.126772&t=h&doflg=ptk&z=3), rather than (55.42, 24.25), as [referenced for instance by Wikipedia](http://en.wikipedia.org/wiki/Panev%C4%97%C5%BEys_Air_Base).

**Comment by da115115** [comment]
Fixed in bc507ad1e5b6f32093f4c3c58ca168f49fcbe43a ([refdata/ORI/ori_por_best_known_so_far.csv line #10449](http://github.com/opentraveldata/optd/commit/bc507ad1e5b6f32093f4c3c58ca168f49fcbe43a#diff-56f5b1ee42ceaa14e4101670cf175adbR10449))
