### ISSUE TITLE
Querying "Thessaloniki “Macedonia” airport" leads to OpenTREP error.

### ISSUE THREAD

**Issue by lnarboni** [opentraveldata/optd#25]
Asking for 'Thessaloniki “Macedonia” airport' information in search travel but ...
The page is unavailable!

![image](https://f.cloud.github.com/assets/6358343/2169155/0ec3d958-9554-11e3-9825-0f0ae29084ec.png)

![image](https://f.cloud.github.com/assets/6358343/2169141/f24c1f9c-9553-11e3-9507-52a2e98e1ebf.png)

**Comment by da115115** [comment]
See also [the issue #7 on OpenTrep project](http://github.com/trep/opentrep/issues/7).
