### ISSUE TITLE
project cleanup - removal of django code

### ISSUE THREAD

**Issue by wsteitz** [opentraveldata/optd#33]
The project is rather cluttered and contains lots of unused files, especially everything related to the django webservice. Afaik, the webservice code is not used anywhere and is definitely unmaintained. 

I think it would make sense to remove the webservice code from the project, or at least move everything to a dedicated directory. This would clean up the project a lot and make it easier to navigate. Also it helps to focus more on the collected travel data.

What do you think?

**Comment by da115115** [comment]
Moving the Django code into a dedicated directory is a very good idea.

I thought several times to move the data out of the refdata/ directory, right into the root directory; indeed, as the name suggests, that project is dedicated to data only, not that much about a Web application any more. However, the URL/location of our maintained data files (e.g., ori_por_public.csv) has been widely published, and is now used by many developers all around the world. So, we should not remove the data files from refdata/ORI, even though it would make sense to...

Do not hesitate to proceed with the code cleaning.

**Comment by chmduquesne** [comment]
Maybe we could create a second repository, with only the referential data,
and update this one with a post-receive hook?

**Comment by wsteitz** [comment]
I think we should split this in two issues: 
1. moving the django webservice stuff - This is rather unproblematic and I will do this in the next few days.
2. move refdata to project root - -this is desirable but a bit more tricky, since we don't want to break existing code relying on the data. I like chmduquesne's idea about using a different repository. Maybe a different branch is enough. Currently all development is in 'trunk', we could just use 'master' (which is the git default anyhow) for all future development (with the data at top-level) and sync all updates to trunk via a post-receive hook. In trunk we just keep the current directory structure. The nice thing about that approach is, that all new users would see and use the 'new' directory structure. trunk would just be used to keep backwards compatability.

**Comment by chmduquesne** [comment]
I believe using a completely different repository is safer.

Github cannot run post-receive hooks directly, it runs with webhooks: HTTP
requests triggered _after_ code was pushed. The problem of using a branch
is that it can leave the repository in a state where it is not yet
synchronized (the script that synchronizes the branches is running
remotely). So If people (or machines) are pulling from the repo at this
very moment, they can get the repository in a non-consistent state (in the
sense that the situation has not happened yet). Moreover, our
synchronization script needs to handle cases such as "people have pushes
changes that modify the two branches", and "don't run if that push was
self-triggered after the synchronization (in order not to enter in a loop)".

With 2 different repositories, it is easier to secure things: Ideally, we
only allow one github user to do modify the "old" repository (provided that
github lets us do that, which I think it does), and there is less chances
that somebody does a mistake.

My 2 cents.

**Comment by chmduquesne** [comment]
On Sat, Oct 25, 2014 at 1:28 PM, Christophe-Marie Duquesne chmd@chmd.fr wrote:

> (in the sense that the situation has not happened yet)

s/situation/synchronisation

**Comment by da115115** [comment]
I am fine with the suggestions of you both. So, let us create a new Git repository (I suggest to keep the same organisation, namely opentraveldata).

**Comment by wsteitz** [comment]
I moved all the webservice related files, already looks much cleaner.

Regarding the new git repository, I don't have sufficient rights to create a new repository for the opentraveldata organisation. For the naming, I would sugest to name the new repository 'opentraveldata', just like the organisation.

**Comment by da115115** [comment]
You now have the rights to create any new project within the organisation. Feel free to do so.

**Comment by wsteitz** [comment]
The new repo is up https://github.com/opentraveldata/opentraveldata. Since we are planning to move files around, we could also think about renaming them. E.g. we could drop the "ori-". Note that in the existing repo (which will be synced) all paths and names will be kept exactly as they are now.

**Comment by da115115** [comment]
Yes, it would make perfect sense to rename the files as well!

**Comment by wsteitz** [comment]
Some open questions regarding the reorganisation
1. do we want everything currently in 'refdata' at toplevel? Or just a subset or just what is in "ORI"?
2. do we drop the "ori_" (e.g. in ori_airlines.csv or ori_por_public.csv) or replace it with something else?

**Comment by wsteitz** [comment]
All data is now uploaded to the new repo and  "ori_" is replaced with "optd_". At toplevel, we currently have 3 folders: 'tools', 'data' and 'opentraveldata'. 'data' contains the collected data. 'opentraveldata' the files curated by us. all scripts are located in 'tools'. 

This is just my take at organizing the files. Please comment here or just commit any changes you want to the layout.

**Comment by chmduquesne** [comment]
The "new" repository, opentraveldata/opentraveldata, is watched by travis. If there is any commit pushed, a synchronisation script which is triggered: It opens the file .travis/synchronization_file_map.csv, where it expects, on each line, to find 2 filenames separated by the character '^', in the order: old, new. It makes sure the files exist in both repositorie, then copies the file from the new repo to the old repo. After all of that is done, it commits the changes to the old repo, and pushes them.

Note about the security of this setup: the ssh key used for pushing is held, encrypted, in the new repo. No one but the guys from travis can decrypt it. This means that we only have to trust travis not to mess up with the repo.

**Comment by chmduquesne** [comment]
By the way, we can use travis to do more than synchronising (e.g. run some sanity checks or transformations every time we push). I have set up a small framework for that. Have a look: https://github.com/opentraveldata/opentraveldata/tree/master/.travis/hooks

**Comment by wsteitz** [comment]
I changed the README files of both the new and the old repository. Now it is time to make the old repo read-only

**Comment by chmduquesne** [comment]
I created a group "bots", and put "opentraveldata-bot" into it. I removed the group "developers" from the teams who have access to optd, and I replaced it with "bots".
