### ISSUE TITLE
Create the user opentraveldata@1adev.com

### ISSUE THREAD

**Issue by chmduquesne** [opentraveldata/optd#34]
We would like to setup a dedicated github user for pushing to this repo, and close the push access of other users. This user needs to have an email address: we were thinking about opentraveldata@1adev.com.

We want to guarantee that the synchronization is maintained between the "clean" project opentraveldata and this repository, and since we want to script this synchronization, we think it is preferable that no other user can push here.

**Comment by da115115** [comment]
The user opentraveldata@1adev.com has been created. There are a few aliases as well: open-travel-data@1adev.com, data@1adev.com, open-data@1adev.com, opendata@1adev.com

**Comment by chmduquesne** [comment]
I created the github user opentraveldata-bot, with the email address opentraveldata@1adev.com. I had github send a verification email. How do I access the email account so that I can verify the address?

I will send you the password of the github account via other means (in case you want to change anything)

**Comment by chmduquesne** [comment]
Ok done. Actually no need to exchange the password of the account: since you own the email address, you can change it anytime.
