### ISSUE TITLE
aerosvit (iata code vv) missing from optd_airlines.csv

### ISSUE THREAD

**Issue by dashaDubin** [opentraveldata/optd#36]
Hi,
could you please add aerosvit airlines to the optd_airlines list?
Here is the reference on Wikipedia: https://en.wikipedia.org/wiki/Aerosvit_Airlines
Thank you! :)

Regards,
Dasha

**Comment by da115115** [comment]
Just for your information, the optd project is no longer maintained. [opentraveldata](https://github.com/opentraveldata/opentraveldata) is the one maintained. However, optd should be a replicate of opentraveldata.

AeroSvit is in the [optd_airlines.csv file, line #36](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airlines.csv#L36).
So, you may not have updated your GitHub repository.
