### ISSUE TITLE
ori_airline_alliance_membership.csv: Overlapping Date Range for US airways

### ISSUE THREAD

**Issue by nishaj** [opentraveldata/optd#38]
Hi All, 
For the following US airways, The "to_date" for the first record is same as the "from_date" of the second record. 
Star Alliance^Member^US^US Airways^2004-05-01^2014-03-31^1
OneWorld^Affiliate^US^US Airways^2014-03-31^^

So for 31st March 2014 departure date, we are unable to determine the alliance name and type.

Can you please correct this data?

Regards,
Nishaj

**Comment by wsteitz** [comment]
Hi Nishaj,

thanks for detecting this! Do you want to open a PR?

Please note that this repository and the ori_airline_alliance_membership.csv file you mentioned are deprecated. All development is happening in the [opentraveldata](https://github.com/opentraveldata/opentraveldata) repository and [optd_airline_alliance_membership.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_alliance_membership.csv) is the file you should be using.

**Comment by wsteitz** [comment]
Fixed by [this commit](https://github.com/opentraveldata/opentraveldata/commit/741cd215edd70bd05a1d828d6df1f33023aa8229).

**Comment by nishaj** [comment]
Thanks Wolfgang for the quick fix.
