### ISSUE TITLE
[ori_por_public] Wrong timezone or name

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/optd#8]
Some lines have weird _timezone_, _name_, _asciiname_ and _city_name_, for example QAF.
I think it would be better to have an empty field when we are not sure of the content.

We could also remove some trailing characters in those fields, like _:_ or _/_.

**Comment by da115115** [comment]
Fixed with d2035e084718b759e176084039884ad8a6b9200b

**Comment by alexprengere** [comment]
This seems to be fixed for timezone, but QAF still has weird data for name, asciiname and city_name. You may update GeoBases to check out the new data you generated.

**Comment by da115115** [comment]
Sure. That issue is tracked by issue #7, which you created two days ago.

**Comment by alexprengere** [comment]
Actually, imo, #7 only tracks the form of the data (case inconsistency over the different rows), whereas this issue tracks the content problems (_name = offline_ for example). A general way of handling "unsure" data could be to just leave empty fields.
